name: framy_generator
description: A convenient code generator for app styleguide, gallery, storyboard and more.
version: 0.3.3
repository: https://github.com/Fidev-io/framy
homepage: https://framy.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  glob: ^2.0.1
  analyzer: 1.3.0
  framy_annotation: ^0.1.5
  yaml: ^3.1.0
  pedantic: ^1.9.2

dev_dependencies:
  build_runner: ^1.10.0
  test: any
  mockito: any
  #source_gen_test:
  #  git:
  #    url: https://github.com/Fidev-io/source_gen_test.git

#dependency_overrides:
#  framy_annotation:
#    path: ../framy_annotation

